const { exec } = require('child_process');
const fs = require('fs');
const path = require('path');

const ERROR_FILE_PATH = path.join(__dirname, '../error.md');

function runCommand(command) {
  return new Promise((resolve) => {
    console.log(`Executing check: ${command}...`);
    exec(command, (error, stdout, stderr) => {
      resolve({
        code: error ? error.code : 0,
        stdout: stdout || '',
        stderr: stderr || ''
      });
    });
  });
}

async function main() {
  console.log('=== NDABAS COMPILATION & ERROR TRACKER ===');
  
  // 1. Run TypeScript Compilation Check (tsc --noEmit)
  const tsResult = await runCommand('npx tsc --noEmit');
  
  const parsedErrors = [];
  
  // Regular expression to parse TypeScript error format:
  // src/app/page.tsx(45,12): error TS2304: Cannot find name 'x'.
  const tsErrorRegex = /^([^\s(]+)\((\d+),(\d+)\):\s+error\s+(TS\d+):\s+(.+)$/gm;
  
  let match;
  while ((match = tsErrorRegex.exec(tsResult.stdout + '\n' + tsResult.stderr)) !== null) {
    parsedErrors.push({
      file: match[1],
      line: parseInt(match[2]),
      col: parseInt(match[3]),
      code: match[4],
      message: match[5].trim(),
      type: 'TypeScript'
    });
  }

  // 2. Also run Next.js build trace or eslint if required
  // For standard next project, let's keep it to TypeScript checks, which are the main source of compile errors.
  
  console.log(`TypeScript check completed with ${parsedErrors.length} error(s).`);
  
  // 3. Construct the error.md file content
  let mdContent = `# Ndabas Attorneys Compilation Error Log\n\n`;
  mdContent += `> This file is automatically generated by \`scripts/check-errors.js\`. It tracks active TypeScript and linting errors in the terminal and guides automated remediation.\n\n`;
  mdContent += `### Last Checked: ${new Date().toLocaleString()}\n`;
  mdContent += `### System Status: ${parsedErrors.length === 0 ? '🟢 CLEAN (No compile errors)' : `🔴 ERROR (${parsedErrors.length} errors active)`}\n\n`;
  
  if (parsedErrors.length === 0) {
    mdContent += `## Active Errors\n\n🟢 All compilation, linting, and type checks are passing. Excellent job!\n\n`;
  } else {
    mdContent += `## Active Errors\n\n`;
    mdContent += `| File Path | Line:Col | Type | Error Code | Error Message | Status | Handled By |\n`;
    mdContent += `| :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n`;
    
    parsedErrors.forEach(err => {
      mdContent += `| \`${err.file}\` | \`L${err.line}:${err.col}\` | ${err.type} | \`${err.code}\` | ${err.message} | 🔴 Unresolved | \`codebase_investigator\` |\n`;
    });
    
    mdContent += `\n`;
    mdContent += `## Auto-Resolution Guide\n`;
    mdContent += `1. **Read** this file to find active compilation errors.\n`;
    mdContent += `2. **Analyze** the specific file and error code listed.\n`;
    mdContent += `3. **Apply** the surgical fix directly via the edit tools.\n`;
    mdContent += `4. **Re-run** \`node scripts/check-errors.js\` to update the ledger and verify the fix.\n`;
  }
  
  mdContent += `\n---\n\n`;
  
  // Append historical error remediation log if it existed previously
  let historySection = `## Resolution History\n\n| Date | File | Error | Fixed By | Method / Commit |\n| :--- | :--- | :--- | :--- | :--- |\n`;
  
  if (fs.existsSync(ERROR_FILE_PATH)) {
    try {
      const oldContent = fs.readFileSync(ERROR_FILE_PATH, 'utf8');
      const startHistIdx = oldContent.indexOf('## Resolution History');
      if (startHistIdx !== -1) {
        historySection = oldContent.substring(startHistIdx);
      }
    } catch (e) {
      console.warn('Could not read existing history section:', e);
    }
  } else {
    // Write an initial empty row
    historySection += `| 2026-07-15 | \`src/app/page.tsx\` | Initial template checks | \`codebase_investigator\` | Set up workspace |\n`;
  }
  
  mdContent += historySection;
  
  fs.writeFileSync(ERROR_FILE_PATH, mdContent, 'utf8');
  console.log(`Successfully updated ${ERROR_FILE_PATH} with status.`);
  
  if (parsedErrors.length > 0) {
    console.log('\n--- ACTIVE ERRORS DETECTED ---');
    parsedErrors.forEach(err => {
      console.log(`[${err.type}] ${err.file}:${err.line}:${err.col} - ${err.code}: ${err.message}`);
    });
    process.exit(1);
  } else {
    console.log('\n🟢 ALL CHECKS PASSED SUCCESSFULLY!');
    process.exit(0);
  }
}

main();
